"""init

Revision ID: 587975be5229
Revises: 
Create Date: 2019-07-07 17:25:08.142870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587975be5229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('qq', sa.Integer(), nullable=True),
    sa.Column('usrObj', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
