"""update user

Revision ID: 2497ad388062
Revises: eb9aed0bff34
Create Date: 2020-05-06 12:10:27.427814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2497ad388062'
down_revision = 'eb9aed0bff34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_constraint('course_student_student_id_fkey', 'course_student', type_='foreignkey')
    op.create_foreign_key(None, 'course_student', 'user', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('score_credit_progress_student_id_fkey', 'score_credit_progress', type_='foreignkey')
    op.create_foreign_key(None, 'score_credit_progress', 'user', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('score_plan_student_id_fkey', 'score_plan', type_='foreignkey')
    op.create_foreign_key(None, 'score_plan', 'user', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('user', sa.Column('class', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('cookies', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=64), nullable=False))
    op.drop_constraint('user_student_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'is_bind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_bind', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_student_id_fkey', 'user', 'student', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.drop_column('user', 'cookies')
    op.drop_column('user', 'class')
    op.drop_constraint(None, 'score_plan', type_='foreignkey')
    op.create_foreign_key('score_plan_student_id_fkey', 'score_plan', 'student', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'score_credit_progress', type_='foreignkey')
    op.create_foreign_key('score_credit_progress_student_id_fkey', 'score_credit_progress', 'student', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'course_student', type_='foreignkey')
    op.create_foreign_key('course_student_student_id_fkey', 'course_student', 'student', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_table('student',
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('degree', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('class', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('major', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('institute', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('major_categories', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('cookies', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('student_id', name='student_pkey')
    )
    # ### end Alembic commands ###
