"""fix score

Revision ID: 4101e812bbb4
Revises: ead93f48a985
Create Date: 2020-05-18 00:09:17.573527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4101e812bbb4"
down_revision = "ead93f48a985"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "score_cet", sa.Column("student_id", sa.String(length=32), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_score_cet_student_id_user"),
        "score_cet",
        "user",
        ["student_id"],
        ["student_id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.alter_column("score_cet", "level", existing_type=sa.Float, type_=sa.String(16))
    op.alter_column("score_cet", "total", existing_type=sa.Integer, type_=sa.String(16))
    op.alter_column(
        "score_cet", "listen", existing_type=sa.Integer, type_=sa.String(16)
    )
    op.alter_column("score_cet", "read", existing_type=sa.Integer, type_=sa.String(16))
    op.alter_column("score_cet", "write", existing_type=sa.Integer, type_=sa.String(16))
    op.alter_column(
        "score_cet", "common", existing_type=sa.Integer, type_=sa.String(16)
    )

    op.add_column(
        "score_physic_or_common", sa.Column("cata", sa.String(length=16), nullable=True)
    )
    op.add_column(
        "score_physic_or_common",
        sa.Column("student_id", sa.String(length=32), nullable=False),
    )
    op.alter_column(
        "score_physic_or_common", "credit", existing_type=sa.Float, type_=sa.String(16)
    )
    op.alter_column(
        "score_physic_or_common", "gpa", existing_type=sa.Float, type_=sa.String(16)
    )
    op.create_foreign_key(
        op.f("fk_score_physic_or_common_student_id_user"),
        "score_physic_or_common",
        "user",
        ["student_id"],
        ["student_id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.add_column(
        "score_plan", sa.Column("student_id", sa.String(length=32), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_score_plan_student_id_user"),
        "score_plan",
        "user",
        ["student_id"],
        ["student_id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.alter_column("score_plan", "credit", existing_type=sa.Float, type_=sa.String(16))
    op.alter_column("score_plan", "gpa", existing_type=sa.Float, type_=sa.String(16))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_score_plan_student_id_user"), "score_plan", type_="foreignkey"
    )
    op.drop_column("score_plan", "student_id")
    op.drop_constraint(
        op.f("fk_score_physic_or_common_student_id_user"),
        "score_physic_or_common",
        type_="foreignkey",
    )
    op.drop_column("score_physic_or_common", "student_id")
    op.drop_column("score_physic_or_common", "cata")
    op.drop_constraint(
        op.f("fk_score_cet_student_id_user"), "score_cet", type_="foreignkey"
    )
    op.drop_column("score_cet", "student_id")
    op.alter_column("score_cet", "level", existing_type=sa.String(16), type_=sa.Float)
    op.alter_column("score_cet", "total", existing_type=sa.String(16), type_=sa.Integer)
    op.alter_column(
        "score_cet", "listen", existing_type=sa.String(16), type_=sa.Integer
    )
    op.alter_column("score_cet", "read", existing_type=sa.String(16), type_=sa.Integer)
    op.alter_column("score_cet", "write", existing_type=sa.String(16), type_=sa.Integer)
    op.alter_column(
        "score_cet", "common", existing_type=sa.String(16), type_=sa.Integer
    )
    op.alter_column(
        "score_physic_or_common", "credit", existing_type=sa.String(16), type_=sa.Float
    )
    op.alter_column(
        "score_physic_or_common", "gpa", existing_type=sa.String(16), type_=sa.Float
    )
    op.alter_column("score_plan", "credit", existing_type=sa.String(16), type_=sa.Float)
    op.alter_column("score_plan", "gpa", existing_type=sa.String(16), type_=sa.Float)
    # ### end Alembic commands ###
