"""add table

Revision ID: 64eca6f7553a
Revises: 
Create Date: 2020-04-23 01:27:39.804207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eca6f7553a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('course_table', sa.LargeBinary(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('teacher_name', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('class_time', sa.String(length=64), nullable=True),
    sa.Column('start_week', sa.Integer(), nullable=True),
    sa.Column('end_week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_card', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('bind_qq', sa.String(length=16), nullable=True),
    sa.Column('is_bind', sa.Boolean(), nullable=True),
    sa.Column('cookies', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_course',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.String(length=16), nullable=True),
    sa.Column('term', sa.String(length=64), nullable=True),
    sa.Column('property', sa.String(length=64), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('make_up_score', sa.Float(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_course')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
